import  { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute:"",
    default: "NextJs Blogs",
    template: "%s | NextJs Blogging"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <header className="p-4">
          <p className="inline-block w-full  bg-slate-500  text-white text-2xl"> Header </p>
        </header>
        <div className="ml-4">
          {children}
        </div>
        <footer className="p-4 ">
          <p className="inline-block w-full  bg-slate-800 text-white text-2xl"> Footer </p>
        </footer>
      </body>
    </html>
  );
}
